### ISSUE TITLE
ModuleNotFoundError: No module named 'anki_fen_vis'

### ISSUE THREAD

**Issue by District-Research** [lwerdna/anki-fen-vis#1]
Hi, thanks for the add-on! Sadly it does not work yet, here is an error I get on MacOS 12.6.2:

```
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Chess FEN Visualizer⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/XXX/Library/Application Support/Anki2/addons21/841766736/__init__.py", line 7, in <module>
    from .chess import svg
  File "/Users/XXX/Library/Application Support/Anki2/addons21/841766736/chess/svg.py", line 26, in <module>
    import anki_fen_vis.chess as chess
ModuleNotFoundError: No module named 'anki_fen_vis'
```

Not sure what's going on but will be happy to learn if there is a way to fix this. Cheers!
⁩

**Comment by sunrosa** [comment]
Same issue here.

**Comment by Arkadiy-globallogic** [comment]
It works if you go to the directory with addons and rename directory from `841766736` to `anki_fen_vis`.

Although, it has some other bugs and issues, so probably I'll end up with just pasting screenshots

**Comment by lwerdna** [comment]
Please try the fix put in on April 13: https://github.com/lwerdna/anki-fen-vis/commit/a7ad319e17301cee8305bb5cd62ad0588282915e

I tested it on MacOS 12.3.1 and ⁨2.1.54.
