### ISSUE TITLE
Problem running on Windows 10

### ISSUE THREAD

**Issue by petters-github** [lwerdna/anki-fen-vis#2]
Thank you for this add-on! Out of the box it doesn't work on Windows 10 however.

The problem seems to be that:

`sys.executable.endswith('anki')`

at line 35 of __init__.py returns false. Changing it to sys.executable.endswith('anki.exe') works for Windows.

**Comment by lwerdna** [comment]
Thank you for this. I incorporated your changes in commit: https://github.com/lwerdna/anki-fen-vis/commit/d3063191e843058e689e08cb0e631dc3e940daa8

And the updates should now be on the ankiweb page.
